name: Sync Portal

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  sync-portal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Ghost repo
        uses: actions/checkout@v3
        with:
          repository: TryGhost/Ghost
          path: Ghost

      - name: Checkout the portal repo
        uses: actions/checkout@v3
        with:
          repository: ram0ng1/portal
          path: portal
          token: ${{ secrets.GITHUB_TOKEN }}  # Adicione o token aqui

      - name: Sync portal directory
        run: |
          rsync -av --delete Ghost/apps/portal/ portal/
          cd portal
          git init
          git remote add origin https://github.com/ram0ng1/portal.git
          git fetch origin

          # Verifique se o branch main existe localmente
          git branch -a
          git branch

          # Se o branch main não existir, crie-o a partir de main do remoto
          git checkout -b main origin/main || git checkout -b main

          # Confirme o status e faça o commit e push
          git status
          git add .
          git status
          git commit -m "Sync with Ghost repository" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"

      - name: Modify PoweredBy.js
        run: |
          cd portal
          sed -i 's/Powered by Ghost/Powered by GhostCustom/' src/components/common/PoweredBy.js
          git status
          git add src/components/common/PoweredBy.js
          git commit -m "Remove Powered by Ghost" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"
