name: Sync Portal

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  sync-portal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Ghost repo
        uses: actions/checkout@v3
        with:
          repository: TryGhost/Ghost
          path: Ghost

      - name: Checkout the portal repo
        uses: actions/checkout@v3
        with:
          repository: ram0ng1/portal
          path: portal

      - name: Sync portal directory
        run: |
          rsync -av --delete Ghost/apps/portal/ portal/
          cd portal
          git init
          git remote add origin https://github.com/ram0ng1/portal.git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync with Ghost repository" || echo "No changes to commit"
          git push origin main

      - name: Modify PoweredBy.js
        run: |
          cd portal
          sed -i 's/Powered by Ghost/Powered by GhostCustom/' src/components/common/PoweredBy.js
          git add src/components/common/PoweredBy.js
          git commit -m "Remove Powered by Ghost" || echo "No changes to commit"
          git push origin main
